# Generated by Django 5.2.7 on 2025-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_daycarerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
